
version: '3.0'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    links:
    - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    volumes:
      - .:/data